version: '3.8'

services:
  hikru-api:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: hikru-assessment-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=oracle-db:1521/XE;User Id=hikru_user;Password=HikruUser123;
      - JWT__Secret=YourProductionSecretKeyHere123456789012345678901234567890
      - JWT__Issuer=HikruAPI
      - JWT__Audience=HikruClients
      - Authentication__ApiKey=hikru-api-key-2025
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - hikru-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: hikru-oracle-db
    environment:
      - ORACLE_PWD=HikruPassword123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./database/init-scripts:/opt/oracle/scripts/startup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/HikruPassword123@//localhost:1521/XE", "as", "sysdba", "@/opt/oracle/scripts/startup/healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - hikru-network
    restart: unless-stopped

volumes:
  oracle_data:
    driver: local

networks:
  hikru-network:
    name: hikru-network
    driver: bridge
