-- Oracle Database Setup Script for Assessment Management API
-- Run this script in your Oracle database to create the required table

-- Create ASSESSMENTS table
CREATE TABLE ASSESSMENTS (
    ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITLE NVARCHAR2(100) NOT NULL,
    DESCRIPTION NVARCHAR2(1000) NOT NULL,
    LOCATION NVARCHAR2(200) NOT NULL,
    STATUS NUMBER(1) DEFAULT 0 NOT NULL,
    RECRUITER_ID NUMBER(10) NOT NULL,
    DEPARTMENT_ID NUMBER(10) NOT NULL,
    BUDGET NUMBER(18,2) NOT NULL,
    CLOSING_DATE DATE,
    CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- Create indexes for better performance
CREATE INDEX IDX_ASSESSMENTS_TITLE ON ASSESSMENTS(TITLE);
CREATE INDEX IDX_ASSESSMENTS_STATUS ON ASSESSMENTS(STATUS);
CREATE INDEX IDX_ASSESSMENTS_RECRUITER_ID ON ASSESSMENTS(RECRUITER_ID);
CREATE INDEX IDX_ASSESSMENTS_DEPARTMENT_ID ON ASSESSMENTS(DEPARTMENT_ID);
CREATE INDEX IDX_ASSESSMENTS_CREATED_DATE ON ASSESSMENTS(CREATED_DATE);

-- Add constraints
ALTER TABLE ASSESSMENTS ADD CONSTRAINT CHK_ASSESSMENTS_STATUS 
    CHECK (STATUS IN (0, 1, 2, 3)); -- 0=Draft, 1=Open, 2=Closed, 3=Archived

ALTER TABLE ASSESSMENTS ADD CONSTRAINT CHK_ASSESSMENTS_BUDGET 
    CHECK (BUDGET > 0);

-- Add comments for documentation
COMMENT ON TABLE ASSESSMENTS IS 'Assessment management table for HR recruitment process';
COMMENT ON COLUMN ASSESSMENTS.ID IS 'Unique identifier for the assessment';
COMMENT ON COLUMN ASSESSMENTS.TITLE IS 'Assessment title (max 100 characters)';
COMMENT ON COLUMN ASSESSMENTS.DESCRIPTION IS 'Assessment description (max 1000 characters)';
COMMENT ON COLUMN ASSESSMENTS.LOCATION IS 'Assessment location';
COMMENT ON COLUMN ASSESSMENTS.STATUS IS 'Assessment status: 0=Draft, 1=Open, 2=Closed, 3=Archived';
COMMENT ON COLUMN ASSESSMENTS.RECRUITER_ID IS 'ID of the recruiter responsible for this assessment';
COMMENT ON COLUMN ASSESSMENTS.DEPARTMENT_ID IS 'ID of the department for this assessment';
COMMENT ON COLUMN ASSESSMENTS.BUDGET IS 'Budget allocated for this assessment';
COMMENT ON COLUMN ASSESSMENTS.CLOSING_DATE IS 'Optional closing date for the assessment';
COMMENT ON COLUMN ASSESSMENTS.CREATED_DATE IS 'Timestamp when the assessment was created';
COMMENT ON COLUMN ASSESSMENTS.UPDATED_DATE IS 'Timestamp when the assessment was last updated';

-- Insert sample data for testing
INSERT INTO ASSESSMENTS (TITLE, DESCRIPTION, LOCATION, STATUS, RECRUITER_ID, DEPARTMENT_ID, BUDGET, CLOSING_DATE)
VALUES 
('Senior Software Developer Assessment', 'Comprehensive technical assessment for senior developer position including coding challenges and system design', 'New York Office', 1, 101, 1, 75000.00, DATE '2025-07-15'),
('Marketing Manager Evaluation', 'Strategic marketing assessment focusing on campaign management and analytical skills', 'Los Angeles Office', 1, 102, 2, 65000.00, DATE '2025-07-20'),
('Data Scientist Technical Review', 'Advanced data science assessment covering machine learning, statistics, and data visualization', 'Remote', 0, 103, 3, 85000.00, DATE '2025-08-01'),
('UX Designer Portfolio Review', 'Design assessment including portfolio review and user experience design challenge', 'San Francisco Office', 2, 104, 4, 70000.00, DATE '2025-06-30'),
('Project Manager Leadership Assessment', 'Leadership and project management skills evaluation with scenario-based questions', 'Chicago Office', 1, 105, 5, 80000.00, DATE '2025-07-25');

COMMIT;

-- Create a sequence for auto-incrementing IDs (if not using IDENTITY)
-- CREATE SEQUENCE SEQ_ASSESSMENTS_ID START WITH 1 INCREMENT BY 1;

PRINT 'Assessment table created successfully with sample data!';
