
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: hikru-oracle-db
    environment:
      - ORACLE_PWD=HikruPassword123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init-scripts:/opt/oracle/scripts/startup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/HikruPassword123@//localhost:1521/XE", "as", "sysdba", "@/opt/oracle/scripts/startup/healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - hikru-network

volumes:
  oracle_data:
    driver: local

networks:
  hikru-network:
    name: hikru-network
    driver: bridge
